nelmio_api_doc:
    documentation:
        info:
            title: "Documentation de l'API Gastronomade"
            description: "Ici vous trouverez toutes les routes pour utiliser l'API du site Gastronomade"
            version: '1.0.0'
    areas:
        default:
            path_patterns: [ '^/api' ]
        avis:
            path_patterns: [ '^/api/avis' ]
        user:
            path_patterns: [ '^/api/user' ]
        restaurant:
            path_patterns: [ '^/api/restaurant' ]
        flagship:
            path_patterns: [ '^/api/flagship' ]