nelmio_api_doc:
    documentation:
        info:
            title: 'API Documentation'
            description: 'This is the API documentation for your project.'
            version: '1.0.0'
    areas:
        default:
            path_patterns: [ '^/api' ]