nelmio_api_doc:
    documentation:
        info:
            title: 'API Documentation'
            description: 'This is the API documentation for your project.'
            version: '1.0.0'
    areas:
        default:
            path_patterns: [ '^/api' ]
        avis:
            path_patterns: [ '^/api/avis' ]
        user:
            path_patterns: [ '^/api/user' ]
        restaurant:
            path_patterns: [ '^/api/restaurant' ]
        flagship:
            path_patterns: [ '^/api/flagship' ]

